#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum StatusCode {
    Continue,
    Ok,
    Created,
    LowOnStorageSpace,
    MultipleChoices,
    MovedPermanently,
    MovedTemporarily,
    SeeOther,
    NotModified,
    UseProxy,
    BadRequest,
    Unauthorized,
    PaymentRequired,
    Forbidden,
    NotFound,
    MethodNotAllowed,
    NotAcceptable,
    ProxyAuthenticationRequired,
    RequestTimeout,
    Gone,
    LengthRequired,
    PreconditionFailed,
    RequestEntityTooLarge,
    RequestUriTooLarge,
    UnsupportedMediaType,
    ParameterNotUnderstood,
    ConferenceNotFound,
    NotEnoughBandwidth,
    SessionNotFound,
    MethodNotValidInThisState,
    HeaderFieldNotValidForResource,
    InvalidRange,
    ParameterIsReadOnly,
    AggregateOperationNotAllowed,
    OnlyAggregateOperationAllowed,
    UnsupportedTransport,
    DestinationUnreachable,
    InternalServerError,
    NotImplemented,
    BadGateway,
    ServiceUnavailable,
    GatewayTimeout,
    RtspVersionNotSupported,
    OptionNotSupported,
    Extension(u16, String),
}

impl StatusCode {
    pub fn code(&self) -> u16 {
        match self {
            Self::Continue => 100,
            Self::Ok => 200,
            Self::Created => 201,
            Self::LowOnStorageSpace => 250,
            Self::MultipleChoices => 300,
            Self::MovedPermanently => 301,
            Self::MovedTemporarily => 302,
            Self::SeeOther => 303,
            Self::NotModified => 304,
            Self::UseProxy => 305,
            Self::BadRequest => 400,
            Self::Unauthorized => 401,
            Self::PaymentRequired => 402,
            Self::Forbidden => 403,
            Self::NotFound => 404,
            Self::MethodNotAllowed => 405,
            Self::NotAcceptable => 406,
            Self::ProxyAuthenticationRequired => 407,
            Self::RequestTimeout => 408,
            Self::Gone => 410,
            Self::LengthRequired => 411,
            Self::PreconditionFailed => 412,
            Self::RequestEntityTooLarge => 413,
            Self::RequestUriTooLarge => 414,
            Self::UnsupportedMediaType => 415,
            Self::ParameterNotUnderstood => 451,
            Self::ConferenceNotFound => 452,
            Self::NotEnoughBandwidth => 453,
            Self::SessionNotFound => 454,
            Self::MethodNotValidInThisState => 455,
            Self::HeaderFieldNotValidForResource => 456,
            Self::InvalidRange => 457,
            Self::ParameterIsReadOnly => 458,
            Self::AggregateOperationNotAllowed => 459,
            Self::OnlyAggregateOperationAllowed => 460,
            Self::UnsupportedTransport => 461,
            Self::DestinationUnreachable => 462,
            Self::InternalServerError => 500,
            Self::NotImplemented => 501,
            Self::BadGateway => 502,
            Self::ServiceUnavailable => 503,
            Self::GatewayTimeout => 504,
            Self::RtspVersionNotSupported => 505,
            Self::OptionNotSupported => 551,
            Self::Extension(code, _) => *code,
        }
    }

    pub fn reason_phrase(&self) -> &str {
        match self {
            Self::Continue => "Continue",
            Self::Ok => "OK",
            Self::Created => "Created",
            Self::LowOnStorageSpace => "Low on Storage Space",
            Self::MultipleChoices => "Multiple Choices",
            Self::MovedPermanently => "Moved Permanently",
            Self::MovedTemporarily => "Moved Temporarily",
            Self::SeeOther => "See Other",
            Self::NotModified => "Not Modified",
            Self::UseProxy => "Use Proxy",
            Self::BadRequest => "Bad Request",
            Self::Unauthorized => "Unauthorized",
            Self::PaymentRequired => "Payment Required",
            Self::Forbidden => "Forbidden",
            Self::NotFound => "Not Found",
            Self::MethodNotAllowed => "Method Not Allowed",
            Self::NotAcceptable => "Not Acceptable",
            Self::ProxyAuthenticationRequired => "Proxy Authentication Required",
            Self::RequestTimeout => "Request Time-out",
            Self::Gone => "Gone",
            Self::LengthRequired => "Length Required",
            Self::PreconditionFailed => "Precondition Failed",
            Self::RequestEntityTooLarge => "Request Entity Too Large",
            Self::RequestUriTooLarge => "Request-URI Too Large",
            Self::UnsupportedMediaType => "Unsupported Media Type",
            Self::ParameterNotUnderstood => "Parameter Not Understood",
            Self::ConferenceNotFound => "Conference Not Found",
            Self::NotEnoughBandwidth => "Not Enough Bandwidth",
            Self::SessionNotFound => "Session Not Found",
            Self::MethodNotValidInThisState => "Method Not Valid in This State",
            Self::HeaderFieldNotValidForResource => "Header Field Not Valid for Resource",
            Self::InvalidRange => "Invalid Range",
            Self::ParameterIsReadOnly => "Parameter Is Read-Only",
            Self::AggregateOperationNotAllowed => "Aggregate operation not allowed",
            Self::OnlyAggregateOperationAllowed => "Only aggregate operation allowed",
            Self::UnsupportedTransport => "Unsupported transport",
            Self::DestinationUnreachable => "Destination unreachable",
            Self::InternalServerError => "Internal Server Error",
            Self::NotImplemented => "Not Implemented",
            Self::BadGateway => "Bad Gateway",
            Self::ServiceUnavailable => "Service Unavailable",
            Self::GatewayTimeout => "Gateway Time-out",
            Self::RtspVersionNotSupported => "RTSP Version not supported",
            Self::OptionNotSupported => "Option not supported",
            Self::Extension(_, reason_phrase) => reason_phrase,
        }
    }
}

impl From<StatusCode> for u16 {
    fn from(status_code: StatusCode) -> Self {
        status_code.code()
    }
}

impl TryFrom<u16> for StatusCode {
    type Error = u16;

    fn try_from(code: u16) -> Result<Self, Self::Error> {
        Ok(match code {
            100 => Self::Continue,
            200 => Self::Ok,
            201 => Self::Created,
            250 => Self::LowOnStorageSpace,
            300 => Self::MultipleChoices,
            301 => Self::MovedPermanently,
            302 => Self::MovedTemporarily,
            303 => Self::SeeOther,
            304 => Self::NotModified,
            305 => Self::UseProxy,
            400 => Self::BadRequest,
            401 => Self::Unauthorized,
            402 => Self::PaymentRequired,
            403 => Self::Forbidden,
            404 => Self::NotFound,
            405 => Self::MethodNotAllowed,
            406 => Self::NotAcceptable,
            407 => Self::ProxyAuthenticationRequired,
            408 => Self::RequestTimeout,
            410 => Self::Gone,
            411 => Self::LengthRequired,
            412 => Self::PreconditionFailed,
            413 => Self::RequestEntityTooLarge,
            414 => Self::RequestUriTooLarge,
            415 => Self::UnsupportedMediaType,
            451 => Self::ParameterNotUnderstood,
            452 => Self::ConferenceNotFound,
            453 => Self::NotEnoughBandwidth,
            454 => Self::SessionNotFound,
            455 => Self::MethodNotValidInThisState,
            456 => Self::HeaderFieldNotValidForResource,
            457 => Self::InvalidRange,
            458 => Self::ParameterIsReadOnly,
            459 => Self::AggregateOperationNotAllowed,
            460 => Self::OnlyAggregateOperationAllowed,
            461 => Self::UnsupportedTransport,
            462 => Self::DestinationUnreachable,
            500 => Self::InternalServerError,
            501 => Self::NotImplemented,
            502 => Self::BadGateway,
            503 => Self::ServiceUnavailable,
            504 => Self::GatewayTimeout,
            505 => Self::RtspVersionNotSupported,
            551 => Self::OptionNotSupported,
            _ => return Err(code),
        })
    }
}

#[cfg(test)]
#[path = "test/status_code_unittests.rs"]
mod tests;
